# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: uninstall existing golang
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/usr/local/go"
    - "$HOME/go"

- name: create golang directory
  file:
    path: "{{ golang_download_dest }}"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_group  }}"
    mode: a=rx,u+w
  become: yes

- name: download golang
  get_url:
    url: "{{ golang_download_url }}"
    dest: "{{ golang_download_dest }}"
    checksum: "{{ golang_download_checksum }}"
  register: golang_download
  retries: "{{ number_of_retries }}"
  until: golang_download is succeeded
  delay: "{{ retry_delay }}"

- name: install golang
  unarchive:
    src: "{{ golang_download.dest }}"
    dest: /usr/local
    copy: false
    mode: a=rx,u+w
  become: yes

- name: set GOPATH env and add golang bin to PATH for all users
  lineinfile:
    create: true
    state: present
    dest: /etc/profile.d/golang.sh
    line: "{{ item }}"
    mode: a=rx,u+w
  become: yes
  loop: "{{ golang_default_exports + golang_additional_exports }}"

- name: set goproxy for PRC
  shell: "source /etc/profile && go env -w GO111MODULE=on && go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct"