# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: install RHEL EPEL repository
  block:
    - name: add EPEL GPG key
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    - name: install EPEL repository
      package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
  become: yes
  when:
    - ansible_distribution == "RedHat"

- name: install CentOS EPEL package
  package:
    name: epel-release
    state: present
  become: yes
  when:
    - ansible_distribution == "CentOS"

- name: add EPEL repository for openEuler
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL
    baseurl: https://dl.fedoraproject.org/pub/epel/8/Everything/$basearch/
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    enabled: true
  become: yes
  when:
    - ansible_distribution == "openEuler"
